nome = str(input('Informe o nome do Pescador:'))
pescado = float(input('Informe peso total pescado: (kg)'))
print('='*40)
print('\033[34mGOVERNO DO ESTADO DE SÃO PAULO'.center(40))
print('Secretaria da Pesca.\033[m'.center(40))
print('='*40)
print('Taxa de Excesso de Pesca (limite 50kg)'.center(40))
print('-'*40)
print()
print(f'Pescador: {nome}')
if pescado <= 50:
    print(f'Total pescado = {pescado} kilos.')
    print('Limite dentro do permitido: Isento de Multa')
elif pescado >= 51:
    calculo = (pescado - 50)
    taxa = float(calculo * 4.00)
    print(f'Total pescado {pescado:.1f} Kilos \nFora do permitido: {calculo:.1f}Kg\nTarifa de excesso R${taxa:.2f}')
print('='*40)
print('\033[34m Preserve o Mar'.center(40))
